### ISSUE TITLE
Graph not rendered, drag and drop no reaction

### ISSUE THREAD

**Issue by shulter** [STMBL/Servoterm-app#6]
Dragging a conf file into the form field results in no action. A click on reset all of a sudden sends all the data with OK response. No graph is rendered.

**Comment by crinq** [comment]
conf files are only sent if the servoterm is connected and wave data is received (hal is running and term0.send_step > 0)

**Comment by shulter** [comment]
starting HAL seems to work. It's possible to send a conf file then. But still no graph. Power cycling and all works. :)

**Comment by crinq** [comment]
the receive event triggers sending: https://github.com/STMBL/Servoterm-app/blob/master/Servoterm/term.js#L120-L123

you need one starting event (wave data, or reply to a cmd)
